id: PBD084C21
initial_creation_type: ocr
source_metadata:
  volumes:
    09825809a9b1407d951d91f3f98d6243:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཕགས་པ་བྱམས་པའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
